### ISSUE TITLE
Missing option encoding

### ISSUE THREAD

**Issue by xorock** [acelaya/ZF-AcMailer#136]
I'm trying to set default headers encoding:
```
'message_options' => [
                
                /**
                 * Default headers encoding
                 */
                'encoding' => 'UTF-8',
```

and got error:
Service with name "acmailer.mailoptions.default" could not be created. Reason: The option "encoding" does not have a callable "setEncoding" ("setencoding") setter method which must be defined

According to docs this should work.

**Comment by acelaya** [comment]
Right.
That feature is still in master and needs to be tagged.
Let me create the new version.

--
Alejandro Celaya Alastrué

**Comment by xorock** [comment]
I just saw encoding options was added 16 days ago, while last release was 18 days ago. Thank You for quick response.

**Comment by acelaya** [comment]
My intention was to tag it right after merging the pull request, but I have
to say I completely forgot it.

--
Alejandro Celaya Alastrué

El 13 nov. 2016 11:45 a. m., "xorock" <notifications@github.com> escribió:

I just saw encoding options was added 16 days ago, while last release was
18 days ago. Thank You for quick response.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/acelaya/ZF-AcMailer/issues/136#issuecomment-260178479>,
or mute the thread

**Comment by acelaya** [comment]
It's already tagged as `v6.3.0`. It should be available shortly in packagist.

**Comment by bartoszzajac** [comment]
v6.3.0 is still not available when installing/updating by composer

**Comment by acelaya** [comment]
There were some kind of problem with packagist's integration, because it wasn't automatically updated.
I have forced a manual update and now you should be able to install v6.3

**Comment by bartoszzajac** [comment]
It is ok now.
